#!/bin/zsh

# Aliases
alias ls='ls'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias lh='ls -alht'
alias mv='mv -i' # confirm override when moving
alias cp='cp -i' # confirm override when copying

# vim
alias v='nvim'
alias vo='nvim -O'
alias vd='nvim -d'

# screen
alias sls='screen -ls'
alias sr='screen -r'
alias sS='screen -S'

# tmux
alias tm="tmux new -A -s main"
alias tn='tmux new-session -s main'
alias ta='tmux attach'
alias tls='tmux ls'
alias tmv='tmux rename-session -t'
alias tk='tmux kill-session -t'

# navigation
alias zz='z -'
alias cf='cd ~/dotfiles/'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# git
alias gco='git checkout'
alias gcm='git commit -m'
alias gg='git status'
alias gdiff='git diff'
alias gpull='git pull'
alias gpush='git push'
alias glogg='git logg'
alias gbr='git branch'
alias sc="~/dotfiles/scripts/source_control.sh"
alias lg='lazygit'
alias lp='lazygit -p'

# open dotfiles in vim
alias vv="nvim ~/.config/nvim"
alias va="nvim ~/.config/zsh/aliases"
alias vz="nvim ~/.zshrc"
alias vs="nvim ~/.ssh/config"
alias vt="nvim ~/.config/tmux/tmux.conf"

# source files 
alias sz='source ~/.zshrc'
alias sf='source ./.venv/bin/activate'
alias reload='exec zsh'

# freqtrade
alias freqtrade='docker compose run --rm freqtrade'

[ -f "$HOME/.config/zsh/aliases.local" ] && source "$HOME/.config/zsh/aliases.local"
